/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as GetTheGuideRouteImport } from './routes/get-the-guide'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SolutionsRouteImport } from './routes/solutions'
import { Route as StartAProjectRouteImport } from './routes/start-a-project'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as WorkRouteImport } from './routes/work'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminEmailDeliveriesRouteImport } from './routes/admin/email-deliveries'
import { Route as AdminEnquiriesRouteImport } from './routes/admin/enquiries'
import { Route as AdminLoginRouteImport } from './routes/admin/login'
import { Route as AdminResourcesRouteImport } from './routes/admin/resources'
import { Route as SolutionsSlugRouteImport } from './routes/solutions.$slug'
import { Route as WorkSlugRouteImport } from './routes/work.$slug'
import { Route as AdminEnquiriesIdRouteImport } from './routes/admin/enquiries.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const GetTheGuideRoute = GetTheGuideRouteImport.update({
  id: '/get-the-guide',
  path: '/get-the-guide',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SolutionsRoute = SolutionsRouteImport.update({
  id: '/solutions',
  path: '/solutions',
  getParentRoute: () => rootRouteImport,
} as any)
const StartAProjectRoute = StartAProjectRouteImport.update({
  id: '/start-a-project',
  path: '/start-a-project',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkRoute = WorkRouteImport.update({
  id: '/work',
  path: '/work',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminEmailDeliveriesRoute = AdminEmailDeliveriesRouteImport.update({
  id: '/email-deliveries',
  path: '/email-deliveries',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminEnquiriesRoute = AdminEnquiriesRouteImport.update({
  id: '/enquiries',
  path: '/enquiries',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminResourcesRoute = AdminResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => AdminRouteRoute,
} as any)
const SolutionsSlugRoute = SolutionsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => SolutionsRoute,
} as any)
const WorkSlugRoute = WorkSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => WorkRoute,
} as any)
const AdminEnquiriesIdRoute = AdminEnquiriesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AdminEnquiriesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/get-the-guide': typeof GetTheGuideRoute
  '/privacy': typeof PrivacyRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/solutions': typeof SolutionsRouteWithChildren
  '/start-a-project': typeof StartAProjectRoute
  '/terms': typeof TermsRoute
  '/work': typeof WorkRouteWithChildren
  '/admin/email-deliveries': typeof AdminEmailDeliveriesRoute
  '/admin/enquiries': typeof AdminEnquiriesRouteWithChildren
  '/admin/login': typeof AdminLoginRoute
  '/admin/resources': typeof AdminResourcesRoute
  '/solutions/$slug': typeof SolutionsSlugRoute
  '/work/$slug': typeof WorkSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/enquiries/$id': typeof AdminEnquiriesIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/get-the-guide': typeof GetTheGuideRoute
  '/privacy': typeof PrivacyRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/solutions': typeof SolutionsRouteWithChildren
  '/start-a-project': typeof StartAProjectRoute
  '/terms': typeof TermsRoute
  '/work': typeof WorkRouteWithChildren
  '/admin/email-deliveries': typeof AdminEmailDeliveriesRoute
  '/admin/enquiries': typeof AdminEnquiriesRouteWithChildren
  '/admin/login': typeof AdminLoginRoute
  '/admin/resources': typeof AdminResourcesRoute
  '/solutions/$slug': typeof SolutionsSlugRoute
  '/work/$slug': typeof WorkSlugRoute
  '/admin': typeof AdminIndexRoute
  '/admin/enquiries/$id': typeof AdminEnquiriesIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/get-the-guide': typeof GetTheGuideRoute
  '/privacy': typeof PrivacyRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/solutions': typeof SolutionsRouteWithChildren
  '/start-a-project': typeof StartAProjectRoute
  '/terms': typeof TermsRoute
  '/work': typeof WorkRouteWithChildren
  '/admin/email-deliveries': typeof AdminEmailDeliveriesRoute
  '/admin/enquiries': typeof AdminEnquiriesRouteWithChildren
  '/admin/login': typeof AdminLoginRoute
  '/admin/resources': typeof AdminResourcesRoute
  '/solutions/$slug': typeof SolutionsSlugRoute
  '/work/$slug': typeof WorkSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/enquiries/$id': typeof AdminEnquiriesIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/about'
    | '/get-the-guide'
    | '/privacy'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/solutions'
    | '/start-a-project'
    | '/terms'
    | '/work'
    | '/admin/email-deliveries'
    | '/admin/enquiries'
    | '/admin/login'
    | '/admin/resources'
    | '/solutions/$slug'
    | '/work/$slug'
    | '/admin/'
    | '/admin/enquiries/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/get-the-guide'
    | '/privacy'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/solutions'
    | '/start-a-project'
    | '/terms'
    | '/work'
    | '/admin/email-deliveries'
    | '/admin/enquiries'
    | '/admin/login'
    | '/admin/resources'
    | '/solutions/$slug'
    | '/work/$slug'
    | '/admin'
    | '/admin/enquiries/$id'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/about'
    | '/get-the-guide'
    | '/privacy'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/solutions'
    | '/start-a-project'
    | '/terms'
    | '/work'
    | '/admin/email-deliveries'
    | '/admin/enquiries'
    | '/admin/login'
    | '/admin/resources'
    | '/solutions/$slug'
    | '/work/$slug'
    | '/admin/'
    | '/admin/enquiries/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  GetTheGuideRoute: typeof GetTheGuideRoute
  PrivacyRoute: typeof PrivacyRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SolutionsRoute: typeof SolutionsRouteWithChildren
  StartAProjectRoute: typeof StartAProjectRoute
  TermsRoute: typeof TermsRoute
  WorkRoute: typeof WorkRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/get-the-guide': {
      id: '/get-the-guide'
      path: '/get-the-guide'
      fullPath: '/get-the-guide'
      preLoaderRoute: typeof GetTheGuideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solutions': {
      id: '/solutions'
      path: '/solutions'
      fullPath: '/solutions'
      preLoaderRoute: typeof SolutionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/start-a-project': {
      id: '/start-a-project'
      path: '/start-a-project'
      fullPath: '/start-a-project'
      preLoaderRoute: typeof StartAProjectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/work': {
      id: '/work'
      path: '/work'
      fullPath: '/work'
      preLoaderRoute: typeof WorkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/email-deliveries': {
      id: '/admin/email-deliveries'
      path: '/email-deliveries'
      fullPath: '/admin/email-deliveries'
      preLoaderRoute: typeof AdminEmailDeliveriesRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/enquiries': {
      id: '/admin/enquiries'
      path: '/enquiries'
      fullPath: '/admin/enquiries'
      preLoaderRoute: typeof AdminEnquiriesRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/resources': {
      id: '/admin/resources'
      path: '/resources'
      fullPath: '/admin/resources'
      preLoaderRoute: typeof AdminResourcesRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/solutions/$slug': {
      id: '/solutions/$slug'
      path: '/$slug'
      fullPath: '/solutions/$slug'
      preLoaderRoute: typeof SolutionsSlugRouteImport
      parentRoute: typeof SolutionsRoute
    }
    '/work/$slug': {
      id: '/work/$slug'
      path: '/$slug'
      fullPath: '/work/$slug'
      preLoaderRoute: typeof WorkSlugRouteImport
      parentRoute: typeof WorkRoute
    }
    '/admin/enquiries/$id': {
      id: '/admin/enquiries/$id'
      path: '/$id'
      fullPath: '/admin/enquiries/$id'
      preLoaderRoute: typeof AdminEnquiriesIdRouteImport
      parentRoute: typeof AdminEnquiriesRoute
    }
  }
}

interface AdminEnquiriesRouteChildren {
  AdminEnquiriesIdRoute: typeof AdminEnquiriesIdRoute
}

const AdminEnquiriesRouteChildren: AdminEnquiriesRouteChildren = {
  AdminEnquiriesIdRoute: AdminEnquiriesIdRoute,
}

const AdminEnquiriesRouteWithChildren = AdminEnquiriesRoute._addFileChildren(
  AdminEnquiriesRouteChildren,
)

interface AdminRouteRouteChildren {
  AdminEmailDeliveriesRoute: typeof AdminEmailDeliveriesRoute
  AdminEnquiriesRoute: typeof AdminEnquiriesRouteWithChildren
  AdminLoginRoute: typeof AdminLoginRoute
  AdminResourcesRoute: typeof AdminResourcesRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminEmailDeliveriesRoute: AdminEmailDeliveriesRoute,
  AdminEnquiriesRoute: AdminEnquiriesRouteWithChildren,
  AdminLoginRoute: AdminLoginRoute,
  AdminResourcesRoute: AdminResourcesRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

interface SolutionsRouteChildren {
  SolutionsSlugRoute: typeof SolutionsSlugRoute
}

const SolutionsRouteChildren: SolutionsRouteChildren = {
  SolutionsSlugRoute: SolutionsSlugRoute,
}

const SolutionsRouteWithChildren = SolutionsRoute._addFileChildren(
  SolutionsRouteChildren,
)

interface WorkRouteChildren {
  WorkSlugRoute: typeof WorkSlugRoute
}

const WorkRouteChildren: WorkRouteChildren = {
  WorkSlugRoute: WorkSlugRoute,
}

const WorkRouteWithChildren = WorkRoute._addFileChildren(WorkRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  GetTheGuideRoute: GetTheGuideRoute,
  PrivacyRoute: PrivacyRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SolutionsRoute: SolutionsRouteWithChildren,
  StartAProjectRoute: StartAProjectRoute,
  TermsRoute: TermsRoute,
  WorkRoute: WorkRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
